### ISSUE TITLE
Unable to use conda-channel-resource

### ISSUE THREAD

**Issue by esc** [qiime2/conda-channel-resource#5]
I have the following config:

```
  - name: esc/label/concourse
    type: conda-channel-resource
    source:
      pkg_name: numba
      uri: https://conda.anaconda.org
      channel: esc/label/concourse
      user: esc
      pass: XXXX
````

But when I try to use it, I get:

```
Traceback (most recent call last):
  File "/opt/resource/out", line 39, in <module>
    sys.argv[1])
  File "/opt/resource/out", line 13, in main
    data = common.ChannelData(path=os.path.join(inpath, params['from']))
KeyError: 'from'
```

**Comment by thermokarst** [comment]
Are you using [concourse ci](https://concourse-ci.org/)? This resource is for the concourse build system --- the `from` param is part of concourse's API for communicating to [resources](https://concourse-ci.org/implementing-resource-types.html). If you _are_ using concourse, have a look at our usage implementation for details: https://github.com/qiime2/busywork/blob/master/ci/master/jinja2/pipelines/distribution.yaml#L331-L335. Here, you will see that we use this repo to _define a new resource type_. Once defined (as `conda-channel`), then we use it all over the place:

```yml
  - name: {{ project.name }}-{{ project.release }}-test-channel
    type: conda-channel
    check_every: 24h
    source:
      pkg_name: {{ project.name }}
      channel: {{ project.test_channel }}
      uri: ((ftp_uri))
      user: ((ftp_user))
      pass: ((ftp_pass))
```

**Comment by esc** [comment]
Yes, I am using it in concourse. Yes, I have defined a resource-type. I also figured out that the `from` needs to be included in the `params` during a `put` step. I still can't get it to pickup my packages however, i.e. I don't know what value `from` should take.

**Comment by thermokarst** [comment]
Hey there @esc, you are using the resource incorrectly:

```yaml
  - name: esc/label/concourse
    type: conda-channel-resource
    source:
      pkg_name: numba
      uri: https://conda.anaconda.org
      channel: esc/label/concourse
      user: esc
      pass: XXXX
```

The above should be changed to:

```yaml
resource_types:
  - name: conda-channel
    type: docker-image
    source:
      repository: qiime2/conda-channel-resource

resources:
  - name: esc/label/concourse
    type: conda-channel
    source:
      pkg_name: numba
      uri: https://conda.anaconda.org
      channel: esc/label/concourse
      user: esc
      pass: XXXX
```

Note the addition of a new `resource_type`, and updating your `esc/label/concourse` resource to _use that new `resource_type`_.

**Comment by esc** [comment]
Oh, sorry, I posted an incomplete config. Here is what I have:

```
resource_types:
- name: conda-channel-resource
  type: registry-image
  source:
    repository: vhaenel/conda-channel-resource
    tag: latest
```

And then later I use:

```
      - put: esc/label/concourse
        params:
          from: /opt/conda/conda-bld/
```

But I still get:

```
Traceback (most recent call last):
  File "/opt/resource/out", line 42, in <module>
    sys.argv[1])
  File "/opt/resource/out", line 20, in main
    raise Exception('No packages found with name: %r' % pkg_name)
Exception: No packages found with name: 'numba'
```

**Comment by esc** [comment]
Specifically, I don't know what the value of `from` should be so that the resource-type can pickup my package.

**Comment by thermokarst** [comment]
```yaml
resource_types:
- name: conda-channel-resource
  type: registry-image
  source:
    repository: vhaenel/conda-channel-resource
    tag: latest

resources:
  - name: esc/label/concourse
    type: conda-channel-resource
    source:
      pkg_name: numba
      uri: https://conda.anaconda.org
      channel: esc/label/concourse
      user: esc
      pass: XXXX

jobs:
  ...
  ...
  - put: esc/label/concourse
    params:
      from: /path/to/wherever/your/build/is
```

The way we use this, is we run [builds](https://github.com/qiime2/busywork/blob/master/ci/master/bin/build.sh) for both linux and darwin, then a concourse task [merges the build folders](https://github.com/qiime2/busywork/blob/master/ci/master/bin/merge.sh). This merged folder is our [`from`](https://github.com/qiime2/busywork/blob/master/ci/master/jinja2/pipelines/distribution.yaml#L157). We specify an `--output-dir` in our conda-build invocation, which makes the build output location predictable. In theory `/opt/conda/conda-bld/` should have your builds in it, but it sounds like from the error you reported above, it does not.
